[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.2"
activityCompose = "1.9.0"
composeBom = "2024.04.01"
retrofitV="2.11.0"
room_version = "2.6.1"
kspVersion = "1.9.0-1.0.13"
okhhtpV = "5.0.0-alpha.14"
daggerV = "2.51.1"
hiltV = "1.2.0"
playServicesLocation = "21.3.0"
permissionV="0.35.1-alpha"
uiTextGoogleFonts = "1.6.8"
dataStore="1.1.1"
composeNavigation = "2.8.0-beta06"
serializationJson = "1.6.3"
composeAnimation = "1.7.0-alpha07"
dokka ="1.9.20"
mockito = "5.4.0"
mockitoCore="5.12.0"
coroutines_version="1.9.0-RC.2"
turbine="1.1.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

#Location
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
accompanist-permission = {group="com.google.accompanist",name="accompanist-permissions", version.ref="permissionV"}

#Network
retrofit = {group="com.squareup.retrofit2", name="retrofit", version.ref="retrofitV"}
gson-converter = {group="com.squareup.retrofit2", name="converter-gson", version.ref="retrofitV"}
okhttp={group="com.squareup.okhttp3", name="okhttp", version.ref="okhhtpV"}
okhttp-logging={group="com.squareup.okhttp3", name="logging-interceptor", version.ref="okhhtpV"}
androidx-lifecycle-livedata-ktx = {group="androidx.lifecycle", name="lifecycle-livedata-ktx", version.ref="lifecycleRuntimeKtx"}
androidx-lifecycle-viewmodel-compose = {group="androidx.lifecycle", name="lifecycle-viewmodel-compose", version.ref="lifecycleRuntimeKtx"}

#Room
room-runtime = {group="androidx.room", name="room-runtime", version.ref="room_version"}
room-compiler =  {group="androidx.room", name="room-compiler", version.ref="room_version"}
room-ktx = {group="androidx.room",name="room-ktx",version="room_version"}

#Dagger Hilt
dagger-hilt-android = {group="com.google.dagger", name="hilt-android", version.ref="daggerV"}
dagger-hilt-navigation-compose = {group="androidx.hilt", name="hilt-navigation-compose", version.ref="hiltV"}
dagger-hilt-compiler = {group="com.google.dagger", name="hilt-android-compiler",version.ref="daggerV"}
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }

#DataStore
datastore-preferences = {group="androidx.datastore",name="datastore-preferences", version.ref="dataStore"}

#Nav
navigation-compose = {module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation"}
kotlinx-serialization-json={module="org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="serializationJson"}

#Animation
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "composeAnimation" }

#Lifecycle
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }

#Dokka
android-documentation-plugin = {group="org.jetbrains.dokka",name="android-documentation-plugin", version.ref="dokka"}

#Test
mockito-kotlin = {group="org.mockito.kotlin", name="mockito-kotlin", version.ref="mockito"}
mockito-core = {group="org.mockito", name="mockito-core", version.ref="mockitoCore"}
kotlinx-coroutines-test = {group="org.jetbrains.kotlinx", name="kotlinx-coroutines-test", version.ref="coroutines_version"}
turbine= {group="app.cash.turbine", name="turbine", version.ref="turbine"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
dagger = {id= "com.google.dagger.hilt.android", version.ref = "daggerV"}
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
dokka = {id="org.jetbrains.dokka", version.ref="dokka"}
